modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"

issueTrackerURL="https://github.com/MrCrayfish/GoblinTraders/issues"

[[mods]]
modId="goblintraders"
version="1.6.1"
displayName="Goblin Traders"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=goblintraders"
displayURL="https://mrcrayfish.com/mods?id=goblintraders"
logoFile="goblintraders_logo.png"
credits="@ItsNahteTV on Twitter for idea. Thank you to @MCVinnyq for creating goblin model"
authors="MrCrayfish"
description='Adds goblins that have unique trades to improve your adventure!'

[[dependencies.goblintraders]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.59,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goblintraders]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goblintraders]]
    modId="configured"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.goblintraders]]
    modId="catalogue"
    mandatory=false
    versionRange="[1.2.0,)"
    ordering="NONE"
    side="CLIENT"

[modproperties.goblintraders]
    catalogueImageIcon="goblintraders_icon.png"
    configuredBackground="minecraft:textures/block/stone.png"
